title: bdziurczak-pages
remote_theme: riggraz/no-style-please
description: Hi, I'm Bartek and I document my journey with computers
author: bdziurczak

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%B %Y" # customize how date is formatted
  show_description: true # show blog description in home page
  lowercase_titles: true # show titles in lowercase in lists









